# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwKOLd2X2fomWBmiqRhK-1J_wEB2VMah
"""

import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Omar"],
    "Score": [85, 90, 78]
}

df = pd.DataFrame(data)
df

